// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package projet_oop;

/************************************************************/
/**class that represent a 2-dim address 
 * 
 * @author Patrick 
 */
public class Address {
	
	private int xCoordinate;
	private int yCoordinate;
	
	
	/************************************************************/
	/**
	 * @param xCoordinate and yCoordinate to represent an address 
	 */
	public Address(int xCoordinate, int yCoordinate) {
		super();
		this.xCoordinate = xCoordinate;
		this.yCoordinate = yCoordinate;
	}


	/************************************************************
	 * Getters and Setters 
	 */
	
	public int getxCoordinate() {
		return xCoordinate;
	}



	public void setxCoordinate(int xCoordinate) {
		this.xCoordinate = xCoordinate;
	}



	public int getyCoordinate() {
		return yCoordinate;
	}



	public void setyCoordinate(int yCoordinate) {
		this.yCoordinate = yCoordinate;
	}

	/************************************************************/

	@Override
	public String toString() {
		return "Adress [xCoordinate=" + xCoordinate + ", yCoordinate=" + yCoordinate + "]";
	}
	
	
	
	
	
	
};
