// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package projet_oop;

/************************************************************/
/**
 * 
 */
public class Dessert extends Dish {
	
	public Dessert(String name, int price, String type) {
		super(name, price, type);
	}
	
	public Dessert(String name, int price) {
		super(name, price, "standard");
	}
	
};
