// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package projet_oop;

/************************************************************/
/**
 * 
 */
public class DishFactory {

	/**
	 * 
	 * @param name 
	 * @param price 
	 * @param type 
	 */
	public static void createMeal(String name, int price, String type) {
	}
};
