// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package projet_oop;

import projet_oop.Meal;

/************************************************************/
/**
 * 
 */
public class FullMeal extends Meal{
	
	
	/**
	 * 
	 */
	public FullMeal(String name, Dish starter, Dish mainDish, Dish dessert) {
		super(name);
		
		String type = "standard";
		
		if(starter instanceof Starter) {
			Starter star = (Starter) starter;
			getListOfDish().add(star);
		}
		
		//TODO implement "else" for case that starter is not of type "Starter"
		
		if(mainDish instanceof MainDish) {
			MainDish main = (MainDish) mainDish;
			getListOfDish().add(main);
		}
		
		//TODO implement "else" for case that mainDish is not of type "MainDish"
		
		if(dessert instanceof Dessert) {
			Dessert des = (Dessert) dessert;
			getListOfDish().add(des);
		}
		
		//TODO implement "else" for case that dessert is not of type "Dessert"
		
		if((starter.getType() == mainDish.getType()) && (mainDish.getType()==dessert.getType()))
			type = mainDish.getType();
		
		setType(type);
	}
	
	
	
};
