// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package projet_oop;

/************************************************************/
/**
 * 
 */
public class HalfMeal extends Meal {
	
	/**
	 * 
	 */
	public HalfMeal(String name, Dish mainDish, Dish secChoice) {
		super(name);
		
		String type = "standard";
		
		if(mainDish instanceof MainDish) {
			MainDish main = (MainDish) mainDish;
			getListOfDish().add(main);
		}
		
		//TODO implement "else" for case that mainDish is not of type "MainDish"
		
		if(secChoice instanceof Dessert) {
			Dessert des = (Dessert) secChoice;
			getListOfDish().add(des);
		}
		
		else if(secChoice instanceof Starter) {
			Starter des = (Starter) secChoice;
			getListOfDish().add(des);
		}
		
		//TODO implement "else" for case that secChoice is of type "MainDish"
		
		if(mainDish.getType()==secChoice.getType())
			type = mainDish.getType();
		
		setType(type);
	}
	
	
	
	
	
	
	
};
