// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package projet_oop;

/************************************************************/
/**
 * 
 */
public class MainDish extends Dish {
	
	public MainDish(String name, int price, String type) {
		super(name, price, type);
	}
	
	public MainDish(String name, int price) {
		super(name, price, "standard");
	}

};
