// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package restaurants;


/************************************************************/
/**
 * MealFactory is there to create objects of type Meal (FullMeal or HalfMeal)
 * 
 * @author Patrick
 */
public class MealFactory {

	public MealFactory(){
		super();
	}
	
	
	
	/**
	 * 
	 * @param starter starter of the Meal
	 * @param main main Dish of the Meal
	 * @param dessert dessert of the Meal
	 * @param name name of the FullMeal 
	 * 
	 * this function checks whether entries are correctly casted before execution
	 * 
	 * @return either a full Meal (if parameters are of correct type) or 'null' (if not)
	 */
	public static FullMeal createFullMeal(String name, Dish starter, Dish main, Dish dessert) {
		
		if(starter instanceof Starter && main instanceof MainDish && dessert instanceof Dessert){
			
			Starter start = (Starter) starter;
			MainDish mainD = (MainDish) main;
			Dessert des = (Dessert) dessert;
			
			return new FullMeal(name, start, mainD, des);
		}
		
		else {
			System.out.println("The full Meal: " + name + " was not created. Please verify that 'starter' is of type 'Starter', 'main' is of type 'MainDish' and dessert is of type 'Dessert'");
			return null;
		}
	}
	
	/**
	 * 
	 * @param main main Dish of the Meal
	 * @param secChoice dessert or starter of the Meal
	 * @param name name of the FullMeal 
	 * 
	 * this function checks whether entries are correctly casted before execution
	 * 
	 * @return either a half Meal (if parameters are of correct type) or 'null' (if not)
	 */
	public static HalfMeal createHalfMeal(String name, Dish main, Dish secChoice) {
		
		if(main instanceof MainDish && (secChoice instanceof Starter || secChoice instanceof Dessert))
			return new HalfMeal(name, main, secChoice);
		
		else {
			System.out.println("The half Meal: " + name + " was not created. Please verify that 'main' is of type 'MainDish' and secChoice is either of type 'Dessert' or 'Starter'");
			return null;
		}
	}
}
