// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package projet_oop;


/************************************************************/
/**
 * MealFactory is there to create objects of type Meal (FullMeal or HalfMeal)
 * 
 * @author Patrick
 */
public class MealFactory {

	public MealFactory(){
		super();
	}
	
	
	//TODO
//	/**
//	 * 
//	 * @param starter 
//	 * @param main  
//	 * @param dessert 
//	 */
//	public static void createMeal(Dish starter, Dish main, Dish dessert) {
//	}
}
