// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package projet_oop;

import projet_oop.Dish;

/************************************************************/
/**
 * 
 */
public class MealFactory {

	/**
	 * 
	 * @param starter 
	 * @param main  
	 * @param dessert 
	 */
	public static void createMeal(Dish starter, Dish main, Dish dessert) {
	}
};
