// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package projet_oop;

import java.util.ArrayList;
import java.util.List;

import projet_oop.Dish;

/************************************************************/
/**
 * 
 */
public abstract class Meal {
	
	private String name;
	private List<Dish> listOfDish;
	private String type;
	

	protected Meal(String name) {
		this.name = name;
		listOfDish = new ArrayList<Dish>();
	}
	
	public String getName() {
		return name;
	}



	public void setName(String name) {
		this.name = name;
	}

	

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public List<Dish> getListOfDish() {
		return listOfDish;
	}



	public void setListOfDish(List<Dish> listOfDish) {
		this.listOfDish = listOfDish;
	}
	
	public void getPrice() {
	}

	@Override
	public String toString() {
		return "Meal [name=" + name + ", listOfDish=" + listOfDish + ", type=" + type + "]";
	}
	
	
	
	
};
