// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package customer;

import restaurants.Address;

/************************************************************/
/**
 * 
 */
public class Customer {
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private String surname;
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private String username;
	/**
	 * 
	 */
	private static int counter;
	/**
	 * 
	 */
	private String emailAdress;
	/**
	 * 
	 */
	private String teleNr;
	/**
	 * 
	 */
	private Address address;

	/**
	 * 
	 */
	public void addNotif() {
	}

	/**
	 * 
	 */
	public void removeNotif() {
	}

	/**
	 * 
	 */
	public void registerFidPlan() {
	}

	/**
	 * 
	 */
	public void unregisterFidPlan() {
	}

	/**
	 * 
	 */
	public void placeOrder() {
	}

	/**
	 * 
	 */
	public void accesHistory() {
	}
};
