// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package customer;


/************************************************************/
/**
 * 
 */
public class FideltyCardPlan {
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private Map<E,V> listOfCust; //think about implementing a strategy pattern
};
