// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package customer;

/************************************************************/
/**
 * 
 */
public class MessageBoard {
	/**
	 * 
	 */
	private String name;

	/**
	 * 
	 */
	public void setMessage() {
	}
};
