// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package restaurantSetUp;



/************************************************************/
/**
 * 
 */
public class FullMeal extends Meal{
	
	public FullMeal(){
		super();
	}
	
	
	/**
	 * @param name = name of the meal f.e. "Lucky Luke" 
	 * @param starter = starting dish of the meal
	 * @param mainDish = main dish of the meal
	 * @param dessert = dessert of the meal
	 * @param all three dishes have to be inserted in the order "starter - main dish - dessert" if not an error pops up
	 * 
	 * the constructor checks whether the added dishes are of they same type and names the meal either standard (different types)
	 * or of a type 
	 */
	public FullMeal(String name, Starter starter, MainDish mainDish, Dessert dessert) {
		super(name);
		
		getListOfDish().add(starter);
		getListOfDish().add(mainDish);
		getListOfDish().add(dessert);
		
		String type = "standard";
			
		if((starter.getType() == mainDish.getType()) && (mainDish.getType()==dessert.getType()))
			type = mainDish.getType();
		setType(type);

	}
	
	
	
};
